name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node.js cache
        uses: actions/cache@v1
        with:
          path: web-app/node_modules/
          key: ${CI_COMMIT_REF_SLUG}
      - name: yarn test
        run: |
          cd web-app
          yarn
          yarn test
        env:
          CI: true
